#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
TIDBITS="$ROOT/tidbits"

# --- Generate tidbits/projects.typ ---
PROJECT_DIR="$TIDBITS/projects"
PROJECT_OUT="$TIDBITS/projects.typ"

{
  echo "// Auto-generated by build.sh — do not edit directly"
  echo "// Run ./build.sh to regenerate"
  echo ""

  # Collect all .typ files sorted for deterministic output
  files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$PROJECT_DIR" -maxdepth 1 -name '*.typ' -print0 | sort -z)

  for f in "${files[@]}"; do
    base="$(basename "$f" .typ)"
    alias="p_${base}"
    printf '#import "projects/%s.typ": project as %s\n' "$base" "$alias"
  done

  echo ""
  echo -n "#let all = ("
  first=true
  for f in "${files[@]}"; do
    base="$(basename "$f" .typ)"
    alias="p_${base}"
    if $first; then
      first=false
    else
      echo -n ", "
    fi
    echo -n "$alias"
  done
  echo ")"
} > "$PROJECT_OUT"

echo "Generated $PROJECT_OUT"

# --- Generate tidbits/artwork.typ ---
ART_DIR="$TIDBITS/artwork"
ART_OUT="$TIDBITS/artwork.typ"

{
  echo "// Auto-generated by build.sh — do not edit directly"
  echo "// Run ./build.sh to regenerate"
  echo ""

  files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$ART_DIR" -maxdepth 1 -name '*.typ' -print0 | sort -z)

  for f in "${files[@]}"; do
    base="$(basename "$f" .typ)"
    alias="a_${base}"
    printf '#import "artwork/%s.typ": artwork as %s\n' "$base" "$alias"
  done

  echo ""
  echo -n "#let all = ("
  first=true
  for f in "${files[@]}"; do
    base="$(basename "$f" .typ)"
    alias="a_${base}"
    if $first; then
      first=false
    else
      echo -n ", "
    fi
    echo -n "$alias"
  done
  echo ")"
} > "$ART_OUT"

echo "Generated $ART_OUT"

# --- Optionally compile ---
if command -v typst &>/dev/null; then
  echo "Compiling homepage.typ -> index.html ..."
  typst compile --root "$ROOT" --features html -f html "$ROOT/outputs/homepage.typ" "$ROOT/index.html" 2>&1
else
  echo "typst not found — skipping compilation"
fi
