// Auto-generated by build.sh — do not edit directly
// Run ./build.sh to regenerate

#import "artwork/anatomy_study.typ": artwork as a_anatomy_study
#import "artwork/head_studies.typ": artwork as a_head_studies
#import "artwork/noita.typ": artwork as a_noita
#import "artwork/praedor_monster.typ": artwork as a_praedor_monster
#import "artwork/skeleton_axes.typ": artwork as a_skeleton_axes
#import "artwork/squeeze_sip_and_grind.typ": artwork as a_squeeze_sip_and_grind
#import "artwork/starving_saint.typ": artwork as a_starving_saint
#import "artwork/stoic_and_stonefaced.typ": artwork as a_stoic_and_stonefaced
#import "artwork/streets_of_helsinki_1.typ": artwork as a_streets_of_helsinki_1
#import "artwork/streets_of_helsinki_2.typ": artwork as a_streets_of_helsinki_2
#import "artwork/streets_of_kotka_1.typ": artwork as a_streets_of_kotka_1
#import "artwork/streets_of_kotka_2.typ": artwork as a_streets_of_kotka_2
#import "artwork/streets_of_kotka_3.typ": artwork as a_streets_of_kotka_3
#import "artwork/uni_vs_mia.typ": artwork as a_uni_vs_mia

#let all = (a_anatomy_study, a_head_studies, a_noita, a_praedor_monster, a_skeleton_axes, a_squeeze_sip_and_grind, a_starving_saint, a_stoic_and_stonefaced, a_streets_of_helsinki_1, a_streets_of_helsinki_2, a_streets_of_kotka_1, a_streets_of_kotka_2, a_streets_of_kotka_3, a_uni_vs_mia)
