// Auto-generated by build.sh — do not edit directly
// Run ./build.sh to regenerate

#import "projects/chorded_keyboard.typ": project as p_chorded_keyboard
#import "projects/fractol.typ": project as p_fractol
#import "projects/mini_rt.typ": project as p_mini_rt
#import "projects/mnshell.typ": project as p_mnshell
#import "projects/stick_vim.typ": project as p_stick_vim

#let all = (p_chorded_keyboard, p_fractol, p_mini_rt, p_mnshell, p_stick_vim)
